
services:
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: backend_db
    image: postgres:16
    environment:
      POSTGRES_DB: course_db
      POSTGRES_USER: course_user
      POSTGRES_PASSWORD: course_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
