
services:
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: backend_db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: course_management
      POSTGRES_PASSWORD: course_pass
      POSTGRES_DB: course_management_db
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
