# Generated by Django 5.2.7 on 2025-10-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_published_at_lesson_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
