name: Django Project CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ دریافت کد
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ نصب Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3️⃣ نصب dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4️⃣ ساخت .env (اختیاری، اگر نیاز به Secretها داری)
    - name: Create .env
      run: |
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

    # 5️⃣ اجرای مهاجریشن‌ها
    - name: Run migrations
      run: python manage.py migrate

    # 6️⃣ اجرای تست‌ها روی host runner
    - name: Run tests
      run: |
        export CI=true
        pytest -n 1 . --maxfail=1
