name: Django Project CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3️⃣ Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r core/requirements.txt
        pip install pytest pytest-xdist

    # 4️⃣ Create .env
    - name: Create .env
      run: |
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> core/.env
        echo "DB_USER=${{ secrets.DB_USER }}" >> core/.env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> core/.env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> core/.env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> core/.env

    # 5️⃣ Run migrations
    - name: Run migrations
      working-directory: core
      run: python manage.py migrate

    # 6️⃣ Run all tests
    - name: Run all tests
      working-directory: core
      run: pytest -n 1 . --maxfail=1
